== Codename One Unit Tests

This repository stores a collection of unit test for https://www.codenameone.com[Codename One].

== Test Status

=== Desktop (JavaSE/Simulator)

image:https://travis-ci.org/codenameone/CodenameOne.svg?branch=master["Build Status", link="https://travis-ci.org/codenameone/CodenameOne"]

=== Android

. 5.1 (API Level 22) : image:https://travis-ci.org/shannah/cn1-unit-tests-android.svg?branch=22["Build Status", link="https://travis-ci.org/shannah/cn1-unit-tests-android"]
. 5.0 (API Level 21) : image:https://travis-ci.org/shannah/cn1-unit-tests-android.svg?branch=21["Build Status", link="https://travis-ci.org/shannah/cn1-unit-tests-android"]
. 4.4 (API Level 19) : image:https://travis-ci.org/shannah/cn1-unit-tests-android.svg?branch=19["Build Status", link="https://travis-ci.org/shannah/cn1-unit-tests-android"]
. 4.3 (API Level 18) : image:https://travis-ci.org/shannah/cn1-unit-tests-android.svg?branch=18["Build Status", link="https://travis-ci.org/shannah/cn1-unit-tests-android"]
. 4.2 (API Level 17) : image:https://travis-ci.org/shannah/cn1-unit-tests-android.svg?branch=17["Build Status", link="https://travis-ci.org/shannah/cn1-unit-tests-android"]
. 4.1 (API Level 16) : image:https://travis-ci.org/shannah/cn1-unit-tests-android.svg?branch=16["Build Status", link="https://travis-ci.org/shannah/cn1-unit-tests-android"]
. 4.0 (API Level 15) : image:https://travis-ci.org/shannah/cn1-unit-tests-android.svg?branch=15["Build Status", link="https://travis-ci.org/shannah/cn1-unit-tests-android"]

=== iOS

iOS automated tests coming soon.

=== Javascript

Javascript automated tests coming soon.

=== UWP/Windows 10

UWP/Windows 10 automated tests coming soon.

== Quick Start

Install the latest Codename One CLI tools

[source,bash]
----
$ sudo npm install -g codenameone-cli
----

Clone this repo

[source,bash]
----
$ git clone https://github.com/shannah/cn1-unit-tests
$ cd cn1-unit-tests
$ cn1 test
----

This will run all the unit tests.

== Running Against Specific Codename One Releases

[source,bash]
----
$ cn1 test -version 3.6
----

This would run the unit tests against version 3.6.

== Running Against Codename One Sources

[source,bash]
----
$ cd cn1-unit-tests
$ cn1 test -cn1Sources=/path/to/codenameone
----

Note that the `-cn1Sources` path should point to the parent directory corresponding to the https://github.com/codenameone/CodenameOne[Codename One GIT repository], so it should
have subdirectories `CodenameOne`, `Ports`, etc...

== Running Against Specific Codename One Jar versions

[source,bash]
----
$ cd cn1-unit-tests
$ cn1 test -seJar /path/to/JavaSE.jar \
           -cn1Jar /path/to/CodenameOne.jar \
           -cldcJar /path/to/CLDC11.jar
----

== Running on Device

IMPORTANT: Running tests on device requires a Codename One Enterprise account.

.Running on Android device
[source,bash]
----
$ cd cn1-unit-tests
$ cn1 test -t android
----

NOTE: For more options, such as specifying which device/emulator to run on, signing options, building against sources, see https://github.com/shannah/codenameone-cli/wiki/test#running-on-android[running on android docs for the cn1 command].

== Error Reports and Verbose Logging

Use the `-e` flag to show the stack trace when a test fails.  Use the `-v` flag to show verbose logging.

Use the `s` flag to stop on errors.

== More Options

For more information about the `cn1 test` command, see https://github.com/shannah/codenameone-cli/wiki/test[its wiki page].

== Adding Your Own Tests

This is a community project, so it is my hope that others will add their own tests.  You can add tests in 2 ways.  Begin by forking this project.  Then:

1. Add a unit test to an existing project within the tests directory.  Adding a unit test to an existing project is easy.  Simply add a class which implements `com.codename1.testing.UnitTest` or extends `com.codename1.testing.AbstractTest` to the project's "tests" directory and implement the appropriate methods.  See https://www.codenameone.com/blog/test-it.html[this blog post] for more information or the https://www.codenameone.com/javadoc/com/codename1/testing/package-summary.html[javadocs for the testing package].
2. Create a new Codename One project containing your own unit tests inside the "tests" directory, and add it to the repository.  Then add an entry to the tests.xml file to reference your project. E.g.  If your project is named "MyUnitTests", then you would add a `<test>` tag to the tests.xml file inside the root `<tests>` tag:
+
[source,xml]
----
<test path="tests/MyUnitTests"/>
----

Once you have finished your changes, you should commit a pull request to have them merged into the master branch.
